### ISSUE TITLE
can not be used with :count => 5

### ISSUE THREAD

**Issue by artur79** [grk/polish#1]
got issue:

I18n::InvalidPluralizationData

translation data {:many=>"jest za krótkie (minimalnie {{count}} znaków)", :one=>"jest za krótkie (minimalnie {{count}} znak)", :few=>"jest za krótkie (minimalnie {{count}} znaki)"} can not be used with :count => 5

for code :

POST_CODE_LENGTH = 5..20
validates_length_of :post_code, :within => POST_CODE_LENGTH

**Comment by grk** [comment]
Nie rozumiem. Powinno byc "(minimalnie 5 znakow)", a jest co?

**Comment by artur79** [comment]
sorki, ucieło kod w modelu

validates_length_of :post_code, :within => 5..20

wywala błąd jak powyżej dla tych ustawień, dla 1,2,3,4 jest ok, od 5 już nie.

**Comment by artur79** [comment]
znalazłem co trzeba poprawić, w locale/activerecord.yml trzeba zamienic :many na :other. 
Pozostałe pliki z localami są ok

**Comment by grk** [comment]
Racja, pomieszalem many z other... Musze spec na to napisac jak bede mial czas. Popchne poprawke jak bede w domu, albo mozesz pull request :)

**Comment by grk** [comment]
Fork queue sie popsulo... http://support.github.com/discussions/repos/2773-fork-queue-not-applying

**Comment by grk** [comment]
OK, wersja 0.0.3 jest juz na gemcutter.

**Comment by artur79** [comment]
:)
