### ISSUE TITLE
handling genders in error header

### ISSUE THREAD

**Issue by sufleR** [grk/polish#8]
Is there a possibility to manage genders in error header?
For example:
this code 
 template:
        header:
          one: "%{model} nie został zachowany z powodu jednego błędu"
          few: "%{model} nie został zachowany z powodu %{count} błędów"
          other: "%{model} nie został zachowany z powodu %{count} błędów"

for zwierzę model will generate

"zwierzę nie został zachowany z powodu jednego błędu"
That's wrong in polish.

How to handle this?
What I  want is model specific header probably.

Now I'm working with template text like this:
template:
        header:
          one: "Nie można zapisać z powodu jednego błędu"
          few: "Nie można zapisać z powodu %{count} błędów"
          other: "Nie można zapisać z powodu %{count} błędów"

It's working and it's polish correct but there is no model name.

**Comment by grk** [comment]
You can overwrite error messages per model in locale files in your app. Currently there's no support for gender in i18n.
